"""Allow nullable user_id in complaints

Revision ID: 702423e2d06b
Revises: d79920200542
Create Date: 2025-10-27 00:06:39.335255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702423e2d06b'
down_revision: Union[str, None] = 'd79920200542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add reset_token and reset_token_expiry columns to users table
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    
    # Add admin_reply and assigned_to columns to complaints table
    op.add_column('complaints', sa.Column('admin_reply', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'complaints', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
