ACCESS_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzU4MjI0NDg2fQ.af_LwxezX4MxgqvOx3rk8QqWz6Dxtg_kUG1bPDu4NUQ"

curl -X POST "http://127.0.0.1:8000/internal/ai/complaints" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ACCESS_TOKEN" \
  -d '
{
  "title": "AI Generated Complaint",
  "description": "This is a complaint generated by the AI service",
  "transcript": "AI transcript",
  "language": "en",
  "translated_text": "AI translated text",
  "category": "AI",
  "subcategory": "Generated",
  "department_code": "PD",
  "complaint_metadata": {"ai_model": "Gemini"}
}'